[package]
name = "mario-neural-network"
version = "0.1.0"
authors = [ "mediremi" ]

[lib]
name = "mario_neural_network"

[dependencies]
sdl2 = { version = "0.32.1", features = ["bundled"] }
libc = "0.2.*"